spring:
  profiles:
    group:
      loc:
        - localdb
        - token
        - fcm-loc
      dev:
        - devdb
        - tokendev
        - fcm-dev
    active: loc
  pid:
    file: /home/ubuntu/app/step2/accountApp.pid
