spring:
  profiles:
    group:
      loc:
        - localdb
        - token
      dev:
        - devdb
        - tokendev
    active: dev
  pid:
    file: /home/ubuntu/app/step2/mymate-app-service.pid